<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="118617" started-at="2019-06-09T20:25:58Z" finished-at="2019-06-09T20:27:56Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="118617" started-at="2019-06-09T20:25:58Z" finished-at="2019-06-09T20:27:56Z">
      <class name="com.qa.test.LinkedInPages.HomePageLinkedInTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.qa.test.LinkedInPages.HomePageLinkedInTest@880ec60]" name="setUp" is-config="true" duration-ms="83269" started-at="2019-06-10T01:55:58Z" finished-at="2019-06-10T01:57:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="NumberofSearchResultsTest()[pri:0, instance:com.qa.test.LinkedInPages.HomePageLinkedInTest@880ec60]" name="NumberofSearchResultsTest" duration-ms="34136" started-at="2019-06-10T01:57:21Z" finished-at="2019-06-10T01:57:55Z">
          <exception class="java.lang.IndexOutOfBoundsException">
            <message>
              <![CDATA[Index: 0, Size: 0]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at com.qa.LinkedIn.Pages.LinkedInHomePage.SearchAPerson(LinkedInHomePage.java:37)
	at com.qa.test.LinkedInPages.HomePageLinkedInTest.NumberofSearchResultsTest(HomePageLinkedInTest.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- NumberofSearchResultsTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.test.LinkedInPages.HomePageLinkedInTest@880ec60]" name="tearDown" is-config="true" duration-ms="1126" started-at="2019-06-10T01:57:55Z" finished-at="2019-06-10T01:57:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.qa.test.LinkedInPages.HomePageLinkedInTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
